version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/base:2023.03'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: 'make'
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
