version: 2.1

jobs:
  build:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      # - run:
      #     name: Install SonarCloud dependencies
      #     command: 'apk add curl bash unzip openjdk8'
      - sonarcloud/scan
      # - run:
      #     name: Install dependencies
      #     command: 'sudo apt install -y build-essential'
      - run:
          name: Build project
          command: 'make'

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
