version: 2.1

jobs:
  build:
    docker:
      - image: 'alpine:latest'
    steps:
      - checkout
      - run:
          name: Install SonarCloud dependencies
          command: 'apk add curl bash'
      - sonarcloud/scan
      - run:
          name: Install dependencies
          command: 'apk add build-base'
      - run:
          name: Build project
          command: 'make'

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
